### ISSUE TITLE
Does not build in Qt 6.9.0

### ISSUE THREAD

**Issue by crimsoncor** [mfnboer/atproto#2]
Went to test out Skywalker with Qt 6.9.0 to see if the hanging issues from 6.8.3 are present. atproto isn't building. Seems like maybe some sort of build config issue. Will happily dig in more.

```
In file included from /crypt/code/github/atproto/lib/lexicon/com_atproto_identity.cpp:3:
/crypt/code/github/atproto/lib/lexicon/com_atproto_identity.h:11:13: error: field has incomplete type 'QString'
    QString mDid;
            ^
/crypt/home/jesse/Qt/6.9.0/android_arm64_v8a/include/QtCore/qcontainerfwd.h:37:7: note: forward declaration of 'QString'
class QString;
```

**Comment by crimsoncor** [comment]
pretty simple set of fixes. I think something changed with the includes in 6.9.0 and QString wasn't being included be default in some places. Also seems like test.h doesn't build any more. Doesn't affect Skywalker though

Didn't want to make an entire fork just for these little changes so here is the patch
```
diff --git a/lib/lexicon/app_bsky_feed_include.h b/lib/lexicon/app_bsky_feed_include.h
index 10681c1..d1863e0 100644
--- a/lib/lexicon/app_bsky_feed_include.h
+++ b/lib/lexicon/app_bsky_feed_include.h
@@ -2,6 +2,7 @@
 // License: GPLv3
 #pragma once
 #include <QJsonDocument>
+#include <QString>
 
 // Extra header to break cyclic dependencies
 
diff --git a/lib/lexicon/app_bsky_richtext.h b/lib/lexicon/app_bsky_richtext.h
index 1740d42..b06c239 100644
--- a/lib/lexicon/app_bsky_richtext.h
+++ b/lib/lexicon/app_bsky_richtext.h
@@ -2,6 +2,7 @@
 // License: GPLv3
 #pragma once
 #include <QJsonDocument>
+#include <QString>
 #include <set>
 
 namespace ATProto::AppBskyRichtext {
diff --git a/lib/lexicon/com_atproto_identity.h b/lib/lexicon/com_atproto_identity.h
index 9a84283..ea03126 100644
--- a/lib/lexicon/com_atproto_identity.h
+++ b/lib/lexicon/com_atproto_identity.h
@@ -2,6 +2,7 @@
 // License: GPLv3
 #pragma once
 #include <QJsonDocument>
+#include <QString>
 
 namespace ATProto::ComATProtoIdentity {
 
diff --git a/lib/lexicon/plc_directory.h b/lib/lexicon/plc_directory.h
index 8a308ac..6bf06ad 100644
--- a/lib/lexicon/plc_directory.h
+++ b/lib/lexicon/plc_directory.h
@@ -1,7 +1,9 @@
 // Copyright (C) 2024 Michel de Boer
 // License: GPLv3
 #pragma once
+#include <QDateTime>
 #include <QJsonDocument>
+#include <QString>
 
 namespace ATProto {
 
diff --git a/main.cpp b/main.cpp
index f867cb6..df8527c 100644
--- a/main.cpp
+++ b/main.cpp
@@ -4,6 +4,8 @@
 #include <QGuiApplication>
 #include <QQmlApplicationEngine>
 
+using namespace Qt::Literals::StringLiterals;
+
 int main(int argc, char *argv[])
 {
     //qputenv("QT_SCALE_FACTOR", "0.9");
@@ -11,7 +13,7 @@ int main(int argc, char *argv[])
     qSetMessagePattern("%{time HH:mm:ss.zzz} %{type} %{function}'%{line} %{message}");
 
     QQmlApplicationEngine engine;
-    const QUrl url(u"qrc:/atproto/Main.qml"_qs);
+    const QUrl url(u"qrc:/atproto/Main.qml"_s);
     QObject::connect(&engine, &QQmlApplicationEngine::objectCreationFailed,
         &app, []() { QCoreApplication::exit(-1); },
         Qt::QueuedConnection);

```

**Comment by mfnboer** [comment]
Thanks. Changed header files. That happens.
